server:
  port: 8084
spring:
  application:
    name: document-service
  http:
    multipart:
     max-file-size: 1024KB
     max-request-size: 1024KB
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
security:
  oauth2:
    client:
      clientId: ui3
      clientSecret: ui3-secret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
      preferTokenInfo: false
  sessions: NEVER
eureka:
  instance:
      hostname: localhost
      port: 8761
  client:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/